### ISSUE TITLE
nRF24 protocol

### ISSUE THREAD

**Issue by martinhladil** [sruttloff/arduino-wavemaker-controller#1]
Very nice project to control the pump in an analog way. Thanks for that!

However, have you ever thought about controlling it via nRF24 which is on board? This is the way how master controller speaks to slave controllers wirelessly. I'm thinking about cracking it by myself, I'm just curious if you maybe did some progress here as well.

**Comment by sruttloff** [comment]
Thank you for your interest.
No, I did not want to implement this via the slave function (radio). Quite simply to be able to use other controllers with 10V input at a later time.
The Jebao pumps have now also been replaced and it was sufficient to produce a suitable cable.
